# Generated by Django 4.2.5 on 2023-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("title", models.CharField(blank=True, max_length=35)),
                ("title_align", models.CharField(max_length=255)),
                ("title_font", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=220)),
                ("description_align", models.CharField(max_length=255)),
                ("description_font", models.CharField(max_length=255)),
                ("colour", models.CharField(default="rgb(0, 0, 0)", max_length=20)),
                ("is_favourite", models.BooleanField(default=False)),
            ],
        ),
    ]
