# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="description_align",
            field=models.CharField(
                choices=[("left", "left"), ("center", "center"), ("right", "right")],
                default="left",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="description_font",
            field=models.CharField(
                choices=[
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier New", "Courier New"),
                ],
                default="Arial",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="title_align",
            field=models.CharField(
                choices=[("left", "left"), ("center", "center"), ("right", "right")],
                default="left",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="title_font",
            field=models.CharField(
                choices=[
                    ("Arial", "Arial"),
                    ("Times New Roman", "Times New Roman"),
                    ("Courier New", "Courier New"),
                ],
                default="Arial",
                max_length=255,
            ),
        ),
    ]
