# Generated by Django 4.2.5 on 2023-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcard", "0002_alter_postcard_description_align_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcard",
            name="is_favourite",
        ),
        migrations.AlterField(
            model_name="postcard",
            name="colour",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
